### ISSUE TITLE
[FEAT] 프론트엔드 To-Do List

### ISSUE THREAD

**Issue by osmin625** [boostcampaitech5/level3_recsys_finalproject-recsys-07#56]
### Overall
- [x] 서비스 로고 만들기
- [x] 로고 클릭 시 instruction 페이지로 이동
- [x] introduction 페이지 내용 채우기
- [x] 웹사이트 배포하기
- [x] Visualization 페이지 제외하기
- [x] Figure 디자인 강화하기
- [x] custom font family 추가 예정

### Sidebar
- [x] sidebar 열고 접을 때 상단 타이틀에서 발생하는 반응 오류 해결하기 (사이드바 상단 타이틀 배치가 부적절한 듯 (사이즈를 늘리고 줄이면 씹힘)
- [x] sidebar 접혔을 때 링크 수정하기

#### Instance
- [x] Instance 페이지 Grid 배치 수정하기
- [x] Instance 페이지에 분포 figure 추가하기
- [x] 한나 figure을 여러 칼럼에 적용할 수 있도록 범용적으로 바꾸기

#### Evaluation
- [x] Evaluation 페이지를 추천 효과 / 추천 효율 / 사용 품질로 구분하기

## See Also
-
